### ISSUE TITLE
How and why the warping works?

### ISSUE THREAD

**Issue by BotaoPeng98** [IGLICT/SketchDream#2]
Hey! Great work!

I have a question about the details of warping. 

In the equation (2), you use predicted depth map $D_s$ to warp input sketch $S$ at the newest viewpoint $c_1$. But, am I misunderstanding that $c_1$  corresponds to not the input sketch $S$ but a novel view's sketch? 

How could such warping be accurate? Alternatively, $S_1$ acts as a rough, intermediate result that helps MVDream to generate the final images, so the precision of warping is not that that significant.

**Comment by ty625911724** [comment]
Yes, $c_1$ corresponds to a sketch from a novel view rather than the input sketch $S$.

It is true that when the novel view sketch has a rotation angle too large relative to the input sketch, the quality or precision of the sketches degrades. Therefore, we only warp the sketches within a ±45 degree range.

Thank you for your attention.
