### ISSUE TITLE
problems about num_workers setting

### ISSUE THREAD

**Issue by Lanjiong-Li** [IGLICT/SketchDream#8]
when I run **./scripts/mushroom.sh** , it prints a warning: The 'train_dataloader' does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` to `num_workers=223` in the `DataLoader` to improve performance.
I wonder where can I modify num_workers? I guess I can find it here **SketchDream/threestudio/data**, but there are lots of scripts in this folder, should I modify all of them? I also see some comments like _# Multi-process, more quickly, with small bug now_ in **SketchDream/threestudio/data/random_multiview_control_depth.py**. Is it relates to this problem?

**Comment by ty625911724** [comment]
We currently do not suggest to use multi-process with num_worker>0 for dataloader. This problem is inherited from three-studio.
If directly setting num_worker>0, when changing the image render size or other settings, it will not work. 
I have tried to utilize some synchronous tips, but it occasionally caused zombie process. Those comments are related to it and you can try it by yourself.
